### ISSUE TITLE
Support redoc documentation viewer

### ISSUE THREAD

**Issue by kramano** [bootique/bootique-swagger#41]
Let's support [redoc](https://github.com/Redocly/redoc) as documentation renderer/viewer.
It can be used instead of swagger-ui. To configure it just add the dependency:

```
<dependencies>
        <dependency>
            <groupId>io.bootique.swagger</groupId>
            <artifactId>bootique-swagger-redoc</artifactId>
            <version>3.0.M2-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.bootique.swagger</groupId>
            <artifactId>bootique-swagger</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.logback</groupId>
            <artifactId>bootique-logback</artifactId>
            <scope>compile</scope>
        </dependency>
</dependencies> 
```

**Comment by andrus** [comment]
Duplicating my comment in the #42 PR:

Using this PR I was able to experiment with Redoc. Looks like embedding a Redoc web console is kind of moot. Redoc provides a CLI tool to package the console into a single HTML file (that can be included in a Bootique app if needed) :

```
npx @redocly/cli build-docs openapi.json 
```

This will work well with the existing `--generate-spec` command
